package view;

public enum Menus {
    LOGIN_MENU,
    MAIN_MENU,
    PROFILE_MENU,
    TEAM_MENU,
    TASKS_PAGE,
    CALENDAR_MENU,
    EXIT,
    NOTIFICATION_BAR,
    TEAM_SELECTION,
    SCOREBOARD,
    ROADMAP,
    CHANGE_PASSWORD_MENU,
<<<<<<< HEAD
    BOARD_MENU,
    CHATROOM,
    TEAM_TASKS
=======
    CHANGE_ROLE_MENU
>>>>>>> b4e50c362256f587e6c18bd8f7b6e6898e06cdc0
}
